### ISSUE TITLE
Non insulated wire

### ISSUE THREAD

**Issue by eirikm** [stingray127/handwirehotswap#3]
What is the diameter of the non isolated wire you are using? What is it called? And where can I buy it?

**Comment by stingray127** [comment]
I used aluminum solid core 24 SWG wire, and I think the specific roll I bought was from Home Depot for hanging picture frames or something random.

24 SWG is ~0.558mm diameter, anything around .5mm dia should work fine.

You can always modify the .scad code to adjust the wire channel dimensions as you see fit.
