### ISSUE TITLE
Readme addition: wiring gauge

### ISSUE THREAD

**Issue by pfn** [stingray127/handwirehotswap#4]
Hi, this design is so very nice, and I built one side of my keyboard with it.... but, I used 26awg solid wire, as a result, I have to shim to crap out of one side of each of my keyswitches to ensure a good electrical connection. For those that come after, could a mention about recommended wiring gauge be added? I did deeper diving into your thingiverse link, and it is mentioned there, but consider this github to be your one-stop-shop, it would be great to have it mentioned.

I'm going to be building my second side of keyboard with 26awg still (because I'm too lazy to go to the store to buy new wire), but I will triple wrap the other terminal to ensure a good connection.

Thanks @stingray127 !

**Comment by stingray127** [comment]
Added wire gauges to the README. Good luck with the build!
