### ISSUE TITLE
About the assembly of the key swiches

### ISSUE THREAD

**Issue by fyang93** [stingray127/handwirehotswap#5]
Thank you for the brilliant work first.
I am planning to build a keyboard with your design but I got very confused after reading your build log.
So in my understanding, the side of diode should be hided in the case, as shown in [this picture](https://github.com/stingray127/handwirehotswap/blob/main/Matrix/img/row/0.jpg), where the key swiches are attached to the opposite side, the side without the diode.
But weirdly, in [another picture](https://github.com/stingray127/handwirehotswap/blob/main/Matrix/img/row/7.jpg), the key swiches are inserted underneath but attached to the side with diode slot.
This really confused me a lot, since I don't have any experience building a keyboard before. I would appreciate that if you may kindly give me some hints.

**Comment by stingray127** [comment]
Sorry about this, there are two versions of sockets used in the assembly guide photos, and I completely didn't realize this would be an issue in the guide. I will update the guide to only v4 photos eventually.

In the v4 sockets, the diode will be almost touching the bottom of the switch.
